### ISSUE TITLE
N-dimensional cubes

### ISSUE THREAD

**Issue by AlecThomson** [simonrw/rust-fitsio#232]
Hi there,

I'll just preface this with the fact that I'm very new to rust, so apologies in advance if this is user error on my part. I'm looking to manipulate multi-dimension arrays stored in FITS. It looks like `fitsio` only supports 2D images at the moment, however. Here's an example:

```rust
fn read_fits_cube(filename: &str) -> ArrayD<f32> {
    let mut f = FitsFile::open(filename).unwrap();
    let hdu = f.primary_hdu().unwrap();
    if let HduInfo::ImageInfo { shape, .. } = &hdu.info {
        println!("Image is {}-dimensional", shape.len());
        println!("Found image with shape {:?}", shape);
    }
    let data = hdu.read_image(&mut f).unwrap();
    data
}
```

I've tested this on 2D, 3D, and 4D FITS data resulting in:
```
Image is 2-dimensional
Found image with shape [81, 75]
Original FITS cube shape: [81, 75]

Image is 3-dimensional
Found image with shape [288, 81, 75]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShapeError/IncompatibleShape: incompatible shapes', /Users/tho822/.cargo/git/checkouts/rust-fitsio-744bbf3dd7e93ff9/858c67d/fitsio/src/ndarray_compat.rs:232:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Image is 4-dimensional
Found image with shape [288, 1, 81, 75]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShapeError/IncompatibleShape: incompatible shapes', /Users/tho822/.cargo/git/checkouts/rust-fitsio-744bbf3dd7e93ff9/858c67d/fitsio/src/ndarray_compat.rs:232:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at `ndarray_compat.rs`, the error points to:
```rust
    fn read_image(fits_file: &mut FitsFile, hdu: &FitsHdu) -> Result<Self> {
        match hdu.info {
            HduInfo::ImageInfo { ref shape, .. } => {
                let data: Vec<T> = ReadImage::read_image(fits_file, hdu)?;
                let shape: Vec<usize> = (0..2).map(|i| shape[i]).collect();
                let arr = Array::from_shape_vec(shape, data).unwrap();
                Ok(arr)
            }
            _ => unreachable!(),
        }
    }
}
```
Am I right in reading the shape definition as only mapping 2 dimensions? If so, I think we should loop over `(0..ndim)` rather than `(0..2)`.  If `ndim` isn't available at this stage, the FITS header NAXIS should provide the same information

**Comment by AlecThomson** [comment]
Quick update - It looks like this is an easy fix with:
```rust
    fn read_image(fits_file: &mut FitsFile, hdu: &FitsHdu) -> Result<Self> {
        match hdu.info {
            HduInfo::ImageInfo { ref shape, .. } => {
                let data: Vec<T> = ReadImage::read_image(fits_file, hdu)?;
                let shape: Vec<usize> = (0..shape.len()).map(|i| shape[i]).collect();
                let arr = Array::from_shape_vec(shape, data).unwrap();
                Ok(arr)
            }
            _ => unreachable!(),
        }
    }
```
